name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: shadowJar
      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: mobbing-build
          path: build/libs/*.jar
      - name: Upload to Webdav
        uses: bxb100/action-upload-webdav@v1
        with:
          webdav_address: https://webdav.apflkchn.tk/
          webdav_upload_path: "/${{github.repository}}/${{github.run_number}}"
          files: "./build/libs/*.jar"
